s = 'HelloPython'
print('1.', max(s))
print('2.', 'python' in s)
print('3.', 'AB' >= '123')
print('4.', 'AB' < 'ABC')
print('5.', 'ABC' == 'abc')
print('6.', s[2:4])
print('7.', s[:])
print('8.', s[2:2])
print('9.', s[len(s)-2])
print('10.', ord('F'))
print('11.', s.lower())
print('12.', s.upper())
print('13.', s.isdigit())
print('14.', s.isalpha())
print('15.', s.isupper())
print('16.', s.rstrip())
print('17.', s.find('h', 5))
print('18.', s.replace('h', 'H', 1))
str1 = input()
print('19.', str1[0], str1[len(str1)//2], str1[len(str1)-1])
str2 = input()
print('20.', '字符"a"的个数为:', str2.count('a'))